[server]
port=":8000"

#####################################################################
# SSL configuration
#
# [server.ssl]
# key=""
# cert=""

#####################################################################
# Assets configuration
#
# [server.assets]
# folder=""

[session]
secret="3a92de0845c67fc54e6243597e11074f8a2ee823"
expires="72h"

#####################################################################
# Database configuration, by default using SQLite3.
# You can also use postgres and mysql. See the documentation
# for more details.

[database]
driver="sqlite3"
datasource="/Users/jdelsman/drone.sqlite"

[github]
client="1cb1c3e6333dc82fe4bd"
secret="3a92de0845c67fc54e6243597e11074f8a2ee823"
orgs=["hoteltonight"]

# [github_enterprise]
# client=""
# secret=""
# api=""
# url=""
# orgs=[]
# private_mode=false
# open=false

# [bitbucket]
# client=""
# secret=""
# open=false

# [gitlab]
# url=""
# client=""
# secret=""
# skip_verify=false
# open=false

# [gogs]
# url=""
# secret=""
# open=false

#####################################################################
# SMTP configuration for Drone. This is required if you plan
# to send email notifications for build statuses.
#
# [smtp]
# host=""
# port=""
# from=""
# user=""
# pass=""

# [docker]
# cert=""
# key=""

# [worker]
# nodes=[
#   "unix:///var/run/docker.sock",
#   "unix:///var/run/docker.sock"
# ]
